### ISSUE TITLE
La propiedad o campo password deberia agregarse a la tabla Person

### ISSUE THREAD

**Issue by ghost** [nickisainez/proyecto-yasta#11]
# Tipo de Issue
_Mejora en la estructura del proyecto_
# Descripción
El campo password y lastsignin se deberian agregar a la tabla y modelo Person

# Desarrollo
El campo password sera de varchar(100) y el campo lastsignin seria datetime

- 
- Se deberia agregar a la esquema de prisma para realizar nuevamente las migraciones
- Se deberia agregar a la entidad Person en la carpeta entity
- 

Se debera modificar el api enpoint para crear person
 createPerson
https://github.com/nickisainez/proyecto-yasta/blob/1b6f15179ab8552ba020f285511999146f4bd4d3/src/controller/PersonController.ts#L23
Se debe utilizar la libreria bcrypt que ya esta instalado para encriptar la contraseña antes de guardar.

**Comment by MariaGonzalesBaldera** [comment]
Se actualizó la estructura DB y se subió los cambios
